### ISSUE TITLE
Faucet: inability to obtain UMEE tokens, communication with discord, etc

### ISSUE THREAD

**Issue by adamewozniak** [umee-network/fonzie#3]

**Comment by brentxu** [comment]
some people have also been reporting the ability to obtain tokens from the same faucet multiple times during a 12 hour window. Are we able to check on this?

**Comment by khoerling** [comment]
yes, when fonzie is restarted, that 12hr. table is cleared.  i'll have a way to persist the lookup table soon among other updates coming...

**Comment by khoerling** [comment]
the past few days of consistent uptime and  latest improvements to respond with relevant errors, etc...  have resolved this issue
